export const UserActions = {
  GET_PROJECTS: "GET_PROJECTS",
  EDIT_START: "PROJECT_EDIT_START",
  EDIT_DATA: "PROJECT_EDIT_DATA",
  //TOGGLE_ACTIVE: "TOGGLE_PROJECT_ACTIVE",
  EDIT_END: "PROJECT_EDIT_END",
  UPDATE: "UPDATE_PROJECT",
  DELETE: "DELETE_PROJECT"
};

export const HoverActions = {
  OVER: "HOVER_OVER",
  OUT: "HOVER_OUT"
};
