export const UserActions = {
  GET_PROJECTS: "GET_PROJECTS",
  EDIT_START: "PROJECT_EDIT_START",
  EDIT_DATA: "PROJECT_EDIT_DATA",
  EDIT_END: "PROJECT_EDIT_END",
  CREATE_START: "PROJECT_CREATE_START",
  CREATE_DATA: "PROJECT_CREATE_DATA",
  CREATE_END: "PROJECT_CREATE_END",
  ADD_PROJECT: "ADD_NEW_PROJECT",
  UPDATE: "UPDATE_PROJECT",
  DELETE: "DELETE_PROJECT"
};

export const SnackBarMessageActions = {
    MESSAGE: "INFO_MESSAGE"
};

export const DeleteActions = {
  SHOW_MESSAGE: "SHOW_DIALOG_BOX",
  HIDE_MESSAGE: "HIDE_DIALOG_BOX",
};

export const HoverActions = {
  OVER: "HOVER_OVER",
  OUT: "HOVER_OUT"
};
